# The language file that should be used. Prepared are "en" and "de". But feel free to change them or add new ones
language: en

general:
  # Define the maximum amount of waypoints a player can have. Set to 0 to disable the limit
  maxWaypoints: 100

  playerInfoCache:
    # Size of the cache. Auto is 75% of max players (this is the amount set in the server.properties file), but you may change it to your liking
    size: auto
    # Time after the retrieved data about a player is no longer valid and should be updated
    invalidAfter: 24
    # Unit of time of the previous value. Valid options are: NANOSECONDS, MICROSECONDS, MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS
    timeUnit: HOURS

  # These aliases will be used to display the worlds name in a more fancy style.
  # Can also be used to hide the real world structure
  worldNameAliases:
    world: 'World'
    world_nether: 'Nether'
    world_the_end: 'The End'

# You can change the items used in the inventory here
inventory:
  # This is used to fill the bottom row in the overview
  emptyItem: GRAY_STAINED_GLASS_PANE
  # This is used as the item for previous/next page in the overview
  arrowItem: ARROW
  # This is used as the item to deselect the active waypoint
  deselectItem: MILK_BUCKET
  # This used in the overview to display a waypoint
  waypointItem: BEACON
  # This is used to activate or select a waypoint
  selectWaypointItem: GREEN_WOOL
  # This is used to delete a waypoint
  deleteWaypointItem: RED_WOOL
  # If the player has admin permissions he can instantly teleport to the position of the waypoint
  teleportToWaypointItem: ENDER_PEARL
  # This is used as the back button
  backItem: BARRIER

# ============================
# WORKS ONLY ON PAPER-SPIGOT
# When not using Paper it just
# wont display anything
# ============================
# Settings for the direction indicator in the action bar.
# I dont recommend to enable this feature if your server gets larger as it may have a performance impact
actionBar:
  # Enable or disable it here
  enabled: true
  # The indicator color is used to show where the waypoint is by changing the color of one of the sections
  indicatorColor: '&4&l'
  # The background color for the sections
  normalColor: '&7&l'
  # Character (or longer texts, but not recommended) to use as the colored direction indicators
  section: 'â¬›'
  # If you turn to much to either side these arrows are highlighted to indicator you need tp turn more
  arrow:
    left: '<-'
    right: '->'
  # The amount of sections used to show if you are walking in the correct direction. Must be an odd number or the plugin will correct it by adding one
  amountOfSections: 35
  # The range of between the center section and most outer section in degrees. So the field of view of the action bar indicator is range x 2
  range: 70

  # When this and the actionbar are enabled the player sees the distance in 3 dimensions and the y axis offset
  crouch:
    # Enable or disable it here
    enabled: true


# Compass will point towards the selected waypoint
# REMEMBER: For this feature to work, the player needs to craft his own compass, I don't want to provide a feature to give away free compasses as it could get
# easily exploited to farm them
compass:
  # Enable or disable it here
  enabled: true
  # When deselecting a waypoint define where the compass should point
  # You can use 'spawn', 'config' or 'ingame'
  # Further information in regards to 'ingame':
  # To make ingame useable you first need to set it with /waypoints defcompass and have the permission waypoints.admin
  # Then reload - or preferably restart the server. To see the change
  defaultLocationType: spawn
  # When you choose 'config' in the previous line, set the location here
  defaultLocation:
    world: 'world'
    x: 0
    y: 0
    z: 0

# To find the exact spot easier when near enough the position where the waypoint was placed changing blocks will appear, but only visible to the player
flashingBlock:
  # Enable or disable it here
  enabled: true
  # The min distance to show up to prevent weird stuff happening
  minDistance: 10
  # The blocks that will appear in a 1-second interval and when the end of the list is reached it will loop to the start
  blocks: [GLASS, GLOWSTONE]

# When further away a beacon will show where the waypoint was placed.
beacon:
  # Enable or disable it here
  enabled: true
  # The min distance before swapping to the flashing block
  minDistance: 50